//Los types deben ser en mayuscula e igual a la variable

export const types = {
    NEW_PRODUCT : 'NEW_PRODUCT',
    NEW_PRODUCT_SUCESS : 'NEW_PRODUCT_SUCESS',
    NEW_PRODUCT_ERROR : 'NEW_PRODUCT_ERROR',

    START_DOWNLOAD_PRODUCTS : 'START_DOWNLOAD_PRODUCTS',
    DOWNLOAD_PRODUCTS_SUCESS : 'DOWNLOAD_PRODUCTS_SUCESS',
    DOWNLOAD_PRODUCTS_ERROR : 'DOWNLOAD_PRODUCTS_ERROR',

    GET_PRODUCT_DELETE: 'GET_PRODUCT_DELETE',
    PRODUCT_DELETE_SUCESS: 'PRODUCT_DELETE_SUCESS',
    PRODUCT_DELETE_ERROR: 'PRODUCT_DELETE_ERROR',

    GET_PRODUCT_EDIT: 'GET_PRODUCT_EDIT',
    START_EDIT_PRODUCT: 'START_EDIT_PRODUCT',
    PRODUCT_EDIT_SUCESS: 'PRODUCT_EDIT_SUCESS',
    PRODUCT_EDIT_ERROR:'PRODUCT_EDIT_ERROR'
}
